### ISSUE TITLE
Can't fetch https response that's 1024 bytes in size

### ISSUE THREAD

**Issue by FROGGS** [libwww-perl/net-http#16]
I'm using SOAP::Lite to query a SOAP service, and sometime the response (including headers) is exactly 1024 bytes long.
When this happens, the SOAP call will result in a timeout because of these lines:
https://github.com/libwww-perl/net-http/blob/master/lib/Net/HTTP/Methods.pm#L276-L279
```perl
                # consume all incoming bytes
                while(1) {
                    my $bytes_read = $self->sysread($_, 1024, length);
                    if(defined $bytes_read) {
                        $new_bytes += $bytes_read;
                        last if $bytes_read < 1024;
                    }
                    [...]
```
I've got a Wireshark log of this case, which highlights this problem.
(like adding debugging statements to that piece of code).

What's the best way to fix this? I'd like to help on this issue...

**Comment by scop** [comment]
#15 seems to discuss the same issue.

**Comment by FROGGS** [comment]
I'm testing #15 now in production...

**Comment by FROGGS** [comment]
The patch in #15 works perfectly. Please apply.
