### ISSUE TITLE
Net::HTTP should not depend on Net::SSL

### ISSUE THREAD

**Issue by nanis** [libwww-perl/Net-HTTP#21]
I realize that `Net::HTTP` *allows* an existing `Net::SSL` to be used for HTTPS connections, but I don't think that is a good reason to list what has always been a very incomplete implementation as a requirement.

**Comment by oalders** [comment]
@nanis that was my mistake that was introduced in the `Dist::Zilla` conversion.  I'll fix it.  Thanks for pointing it out.

**Comment by rwtnorton** [comment]
👍 
Ran into this today while updating.
