### ISSUE TITLE
t/live.t started to fail

### ISSUE THREAD

**Issue by eserte** [libwww-perl/Net-HTTP#53]
www.cpan.org is now a permanent (301) redirect to https://www.cpan.org. This is causing the t/live.t test to fail:
```
perl -Mblib t/live.t 
1..6
# ----------------------------
# 301 Moved Permanently
# Accept-Ranges: bytes
# Connection: close
# Content-Length: 0
# Date: Fri, 01 Sep 2017 07:01:25 GMT
# Location: https://www.cpan.org/
# Retry-After: 0
# Server: Varnish
# Via: 1.1 varnish
# X-Cache: HIT
# X-Cache-Hits: 0
# X-Served-By: cache-hhn1524-HHN
# X-Timer: S1504249286.981957,VS0,VE0
#
Use of uninitialized value $buf in substitution (s///) at t/live.t line 59.
not ok 1 - success
#   Failed test 'success'
#   at t/live.t line 61.
not ok 2
#   Failed test at t/live.t line 62.
#                   undef
#     doesn't match '(?^:text/html)'
not ok 3
#   Failed test at t/live.t line 63.
#                   undef
#     doesn't match '(?^i:</html>)'
Server closed connection without sending any data back at /tmpfs/.cpan-build-cpansand/2017090106/Net-HTTP-6.16-0/blib/lib/Net/HTTP/Methods.pm line 391.
# Looks like you planned 6 tests but ran 3.
# Looks like you failed 3 tests of 3 run.
# Looks like your test exited with 255 just after 3.
```

**Comment by eserte** [comment]
It's hard to find a http-only replacement these days ... but replacing www.cpan.org by search.cpan.org seems to work.

**Comment by ribasushi** [comment]
@eserte http://neverssl.com/ / https://news.ycombinator.com/item?id=13369038

**Comment by genio** [comment]
Thanks for the report and the neverssl.com suggestion. There's now a PR in to fix this. As soon as all CI testing goes through we'll try to get a release cut to fix it in the wild.

**Comment by oalders** [comment]
6.17 has now been released.

**Comment by karenetheridge** [comment]
In the Test-LWP-UserAgent network tests, I've recently switched to httpbin.org for testing various GET/POST/redirect handling.

**Comment by abh** [comment]
http://captive.apple.com/ also doesn't force TLS.

We might add a non-TLS version of CPAN.org (or if it's just for tests, something else ...).
