### ISSUE TITLE
Problems installing on macOS

### ISSUE THREAD

**Issue by 097115** [libwww-perl/Net-HTTP#69]
After `cpanm LWP`, I get the following error:

    --> Working on LWP
    Fetching http://www.cpan.org/authors/id/O/OA/OALDERS/libwww-perl-6.50.tar.gz ... OK
    Configuring libwww-perl-6.50 ... OK
    ==> Found dependencies: Net::HTTP
    --> Working on Net::HTTP
    Fetching http://www.cpan.org/authors/id/O/OA/OALDERS/Net-HTTP-6.19.tar.gz ... OK
    Configuring Net-HTTP-6.19 ... OK
    Building and testing Net-HTTP-6.19 ... FAIL

which leads to this except from the log file:

    t/http.t ............... ok
    Net::HTTPS: SSL connect attempt failed with unknown error error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version at t/live-https.t line 34.
    # Looks like your test exited with 255 before it could output anything.
    t/live-https.t ......... 
    Dubious, test returned 255 (wstat 65280, 0xff00)

Something I can fix here? :)

**Comment by oalders** [comment]
Thanks for reporting @097115! Do you get this error consistently?

**Comment by 097115** [comment]
And you were right, @oalders, I actually WAS able to install it right now. So, it seems the error wasn't on my side then :)

Thanks for a hint, Olaf, closing this.

**Comment by oalders** [comment]
Thanks for the followup @097115!
